# This file was generated by update.sh

{
  "kicad" = {
    kicadVersion = {
      version =			"5.1.9";
      src = {
        rev =			"73d0e3b20dec05c4350efa5b69916eb29a7bfcb5";
        sha256 =		"1cqh3bc9y140hbryfk9qavs2y3lj5sm9q0qjxcf4mm472afzckky";
      };
    };
    libVersion = {
      version =			"5.1.9";
      libSources = {
        i18n.rev =		"04f3231f60d55400cb81564b2cd465a57d5192d5";
        i18n.sha256 =		"04jq1dcag6i2ljjfqrib65mn4wg4c4nmi7i946l3bywc0rkqsx1f";
        symbols.rev =		"6dec5004b6a2679c19d4857bda2f90c5ab3a5726";
        symbols.sha256 =	"0n25rq32jwyigfw26faqraillwv6zbi2ywy26dkz5zqlf5xp56ad";
        templates.rev =		"1ccbaf3704e8ff4030d0915f71e051af621ef7d7";
        templates.sha256 =	"1a8xfcbdbb4ylrb5m7n2jjk9kwvgmlx1pmnn2cwj327a2b3m4jjs";
        footprints.rev =	"302ac78bac21825532f970fb92714fa5973ad79b";
        footprints.sha256 =	"0gyqxryda273hjn2rv8dha461j9bjh054y5dlpiw1wiha65lrf9i";
        packages3d.rev =	"7abe02f30fd79b8f4f66c01589861df7f8f72f04";
        packages3d.sha256 =	"1szcin52fcsyb55bj7xq7lz6ig187dpz3lk7blwab7b9c4dn3c3y";
      };
    };
  };
  "kicad-unstable" = {
    kicadVersion = {
      version =			"2021-03-17";
      src = {
        rev =			"fee3c41c40a70a3ef865f4d83c999cbbc6f18a74";
        sha256 =		"0kim830apprlxivb080wnl694z02w9p043rzqyzss980wlkrxjgw";
      };
    };
    libVersion = {
      version =			"2021-03-17";
      libSources = {
        i18n.rev =		"e89d9a89bec59199c1ade56ee2556591412ab7b0";
        i18n.sha256 =		"04zaqyhj3qr4ymyd3k5vjpcna64j8klpsygcgjcv29s3rdi8glfl";
        symbols.rev =		"3c1d197bf276d0b7cccb9490f12738f54889922d";
        symbols.sha256 =	"17l4bxhn7iys56i0a32rm0rcxaa657miik31ldxr31pmpnk1yyhb";
        templates.rev =		"073d1941c428242a563dcb5301ff5c7479fe9c71";
        templates.sha256 =	"14p06m2zvlzzz2w74y83f2zml7mgv5dhy2nyfkpblanxawrzxv1x";
        footprints.rev =	"964e997877b61806cb800d97e360a6c1bc5fab52";
        footprints.sha256 =	"0i7f40mcwd90b447x64fb58xnpfvn08ai59sg5nm2rbp623dqpvp";
        packages3d.rev =	"d8b7e8c56d535f4d7e46373bf24c754a8403da1f";
        packages3d.sha256 =	"0dh8ixg0w43wzj5h3164dz6l1vl4llwxhi3qcdgj1lgvrs28aywd";
      };
    };
  };
}
